### ISSUE TITLE
v0.4 Test

### ISSUE THREAD

**Issue by Grayfox96** [erickt420/FFXCutsceneRemover#10]
https://www.twitch.tv/videos/921705806
I tested v0.4 using a 1000ms delay:
- manually changed forceload to 1 during the opening cutscene and it warped me to the docks like it should
- didnt crash after tanker
- crashed after Geosgaeno multiple times (cheat engine showed roomnumber = 50 and storyline = 50) (14m49s)
- got no softlock after leaving the menu (i did the menu after geosgaeno)
- i got the cutscene after entering besaid village but i was able to move after wakka asked "You do remember the prayer, right?" (40m38s)
- got softlocked during the first dream cutscene (43m23s), i manually put forceload to 1 and the game continued after the cutscene
- softlocked after i tried to leave the tent during the second night (54m57s), normally you dont even have control in that version of the crusaders tent
- spawned at the wrong spawnpoint (0) after the forced flan fight (1h4m55s)
- never received valefor so i softlocked during the garuda fight, the game forces you to summon her

**Comment by erickt420** [comment]
I discovered a major bug that I am hoping will help with a number of stability issues you've been facing. Basically we were checking memory far too often (and incorrectly) which was causing the various transitions defined in the program to be looking at different values. Let me know how the stability issues work out in v0.5

**Comment by Grayfox96** [comment]
Every issue here has been fixed in v0.5
