### ISSUE TITLE
PostBossBattleTransitions not working

### ISSUE THREAD

**Issue by Ricky-James** [erickt420/FFXCutsceneRemover#15]
Can test by killing Spherimorph. Flashback cutscene after the AP screen should be skipped

**Comment by erickt420** [comment]
This issue has been fixed.

This wasn't working for a number of reasons:
* Deep Pointers for the required memory location were disabled.
* We were reading memory too often and it was causing pretty much all of the checks against a `MemoryWatcher.Old` to fail.
