### ISSUE TITLE
Unable to run the executable

### ISSUE THREAD

**Issue by nightbox69** [erickt420/FFXCutsceneRemover#20]
Getting this error when I'm running the executable on command prompt (with and w/o admin privilege): ![image](https://user-images.githubusercontent.com/3726708/111329423-159b6580-86aa-11eb-9043-fba4215bae26.png)

Also installed .net 5.0 from the specified link from the error message: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64

**Comment by Ricky-James** [comment]
Try 3.1: https://dotnet.microsoft.com/download/dotnet/3.1/runtime

**Comment by nightbox69** [comment]
That fixed the issue. I'll add a PR to the readme to address the requirements to reduce confusion.
