### ISSUE TITLE
With Expert Sphere Grid, the version info isn't shown and the intro isn't skipped

### ISSUE THREAD

**Issue by Ricky-James** [erickt420/FFXCutsceneRemover#44]
The custom text box crashes the game when selecting expert grid

**Comment by Ricky-James** [comment]
Correction: This isn't a crash, it just isn't currently supported.
The custom text box doesn't show and then the "Beginning" cutscene isn't skipped.

**Comment by HannibalSnekter** [comment]
As far as I can tell the beginning is skipped on expert sphere grid, or at least when I run the game with the mod it works fine.
