### ISSUE TITLE
Wantz dialog not triggered on Mt. Gagazet

### ISSUE THREAD

**Issue by boydjt94** [erickt420/FFXCutsceneRemover#63]
Speaking to Wantz on Mt. Gagazet does not trigger him to mention O'aka being imprisoned in Bevelle, therefore making it impossible to access his shop in Macalania Woods in the post-game.

**Comment by Ricky-James** [comment]
The intent here was to skip the cutscene in order to access the shop faster (a beneficial skip for CSR NSG). The casual element of Wantz re-appearing in Macalania wasn't tested

The attached PR should fix this though (coming in 1.4.1)
