### ISSUE TITLE
Remove menu delay during battles

### ISSUE THREAD

**Issue by flobberworm4** [erickt420/FFXCutsceneRemover#7]
This is not related to the cutscene skip mod per se, but I would be totally okay with this being included OpieOP

Would greatly enhance the speedrun, probably the biggest grievance for many experienced FFX players

**Comment by erickt420** [comment]
Any idea how this can be accomplished?

**Comment by Ricky-James** [comment]
I'll close this one since I'm not entirely sure this should be attached to this mod, but it could be interesting to explore as a separate project.
It'd definitely be contentious to mod something that isn't removing a cutscene.
