### ISSUE TITLE
Cutscene Remover Not Skipping Cutscenes

### ISSUE THREAD

**Issue by Cameron1065** [erickt420/FFXCutsceneRemover#79]
For some reason every time I boot the cutscene remover the only cutscene that I can skip is the opening one where Tidus starts off playing Blitzball during the sin attack in Zanarkand. Any other cutscene I attempt to skip gives me no option. I don't know if I am doing it wrong or not, but I've hit every button on my xbox one controller and my keyboard and mouse.

**Comment by Ricky-James** [comment]
Hi Cameron,
It sounds like the Cutscene Remover is not starting correctly at all. The skip you're using is one that's already built into the game.
When it's running correctly, skips will be performed automatically.

I've just updated the instructions to be a bit more specific - please read the updated Usage instructions on the main page [here](https://github.com/erickt420/FFXCutsceneRemover/)

If you still encounter issues, please join us on [Discord](https://discord.gg/X3qXHWG) and we can help out there.
