### ISSUE TITLE
Skip pre-boss cutscenes

### ISSUE THREAD

**Issue by flobberworm4** [erickt420/FFXCutsceneRemover#8]
At the moment most cutscenes prior to a boss fight are not skipped due to their complexity, as the cutscene leads to a battle. If a way was found to skip these and go straight to the fight, this will greatly reduce the amount of cutscenes in the game.

Of course there may not be a consistent way to do this for all boss fights but hopefully there will be

**Comment by HannibalSnekter** [comment]
This can probably be closed now
